In [10]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

### Задание 1.
**Решите линейную систему:**  
__| 1 2 3 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|12|  
| 4 0 6 |&nbsp;*&nbsp;X&nbsp;=&nbsp;| 2|  
| 7 8 9 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 1|__

In [24]:
mtx_A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]]) 
mtx_B = np.array([12, 2, 1])
print(np.linalg.solve(mtx_A, mtx_B))
#np.linalg.lstsq(mtx_A, mtx_B)

[-9.2         0.9         6.46666667]


### Задание 2.
**Найдите псевдорешение:**  
__x + 2y – z = 1  
3x – 4y = 7  
8x – 5y + 2z = 12  
2x – 5z = 7  
11x +4y – 7z = 15__

In [27]:
mtx_C = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, -5, 0], [11, 4, -7]]) 
mtx_D = np.array([1, 7, 12, 7, 15])
#print(np.linalg.lstsq(mtx_C, mtx_D))
np.linalg.lstsq(mtx_C, mtx_D)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

In [15]:
# Проверка
def Q(x, y, z):
    return ((np.linalg.norm(np.dot(mtx_C, [x, y, z]) - mtx_D))**2)
Q(1.15601029, -0.889718  , -0.85029782)

0.6677253445282131

### Задание 3.
**Сколько решений имеет линейная система:**  
__| 1 2 3 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|12|  
| 4 5 6 |&nbsp;*&nbsp;X&nbsp;=&nbsp;| 2|  
| 7 8 9 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 1|__  
__Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.__

In [69]:
mtx_E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
mtx_F = np.array([[12, 2, 1]])
print('Детерминант матрицы равен: ',np.linalg.det(mtx_E))

print('Ранк исходной матрицы: ', np.linalg.matrix_rank(mtx_E, 0.0001))
print('Ранк расширенной матрицы: ', np.linalg.matrix_rank(np.concatenate((mtx_E, mtx_F.T), axis=1), 0.0001))
print('\n"2 != 3" и "Детерминант равен 0" => Данная система не имеет ни одного решения.')

mtx_F.shape
#print(np.linalg.solve(mtx_E, mtx_F))
np.linalg.lstsq(mtx_E, mtx_F.T)

Детерминант матрицы равен:  6.66133814775094e-16
Ранк исходной матрицы:  2
Ранк расширенной матрицы:  3

"2 != 3" и "Детерминант равен 0" => Данная система не имеет ни одного решения.


(array([[-7.69444444],
        [-0.61111111],
        [ 6.47222222]]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

### Задание 4.
**Вычислите LU-разложение матрицы:**  
__| 1&nbsp;&nbsp;&nbsp;2&nbsp;&nbsp;&nbsp;3 |  
| 2 16 21 |  
| 4 28 73 |__  
__После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.__

### Задание 5.
**Найдите нормальное псевдорешение недоопределенной системы:**  
__x + 2y – z = 1  
8x – 5y + 2z = 12__  
__Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.__

### Задание 6.
**Найдите одно из псевдорешений вырожденной системы:**  
__| 1 2 3 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 2|  
| 4 5 6 |&nbsp;*&nbsp;X&nbsp;=&nbsp;| 5|  
| 7 8 9 |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|11|__  
__Попробуйте также отыскать и нормальное псевдорешение.__